# Generated by Django 3.2.6 on 2021-08-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='img_name',
            field=models.TextField(default='name', max_length='20'),
        ),
    ]
