# Generated by Django 3.2.6 on 2021-08-30 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_img_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=35)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('phone_num', models.IntegerField()),
                ('message', models.TextField(max_length='200')),
            ],
        ),
    ]
